### ISSUE TITLE
No Code

### ISSUE THREAD

**Issue by TomTom1229** [aserg-ufmg/JSCity#1]
Needs the code...

**Comment by mtov** [comment]
Hi Tomas, we will make it available in a few weeks. we just need to organize and clean up it before, to make it more easy to use.

**Comment by naveed-ahmad** [comment]
+1 interesting idea. Looking forward to see the code, really want to test city of [Rails](https://github.com/rails/rails) repo :smile:

**Comment by Marak** [comment]
Have a little patience. This project looks really interesting.

If you author's don't want to release it because it's not presentable that's understandable.

With that being said, it will never be perfect. Better to just release something sooner that works without many bells and whistles, but with the expectation it will be improved in the upcoming weeks.

**Comment by naveed-ahmad** [comment]
Waiting.... but agreed. Working code is good enough to share, things can't be perfect ever. Samples in wiki looks dam good.

**Comment by jacob-israel-turner** [comment]
Looking forward to the code being released.  :)

**Comment by Hunter-Github** [comment]
No code - no <strike>cigar</strike> star.

**Comment by farlleyalves** [comment]
OMG!!! Coodeeee pleeeasee!!!

**Comment by landonwilkins** [comment]
+1 code please :heart:

**Comment by newebug** [comment]
+1 Waiting....

**Comment by kelvinlouis** [comment]
Take your time! Looking forward to it.

**Comment by malilovick** [comment]
Hello guys. The JSCITY source code is available 
Any idea , suggestion for improvement would be welcome.

**Comment by Marak** [comment]
Super awesome @malilovick !

Thank you.

Will try to generate a city a bit later. Will let you know if I run into any issues.

**Comment by naveed-ahmad** [comment]
Awesome, will try to generate my city today :)

**Comment by kelvinlouis** [comment]
yay! thanks for publishing the code! some buildings are frighteningly tall ;)
