### ISSUE TITLE
https://github.com/ASERG-UFMG/JSCity/wiki/JSCITY

### ISSUE THREAD

**Issue by Michigan777** [aserg-ufmg/JSCity#12]
https://github.com/ASERG-UFMG/JSCity/wiki/JSCITY

**Comment by malilovick** [comment]
Hi Michigan777 could you explain better this issue ? When I accessed the url informed I was redirected to a not fount page.
The right wiki's url is https://github.com/ASERG-UFMG/JSCity/wiki/JSCITY
