### ISSUE TITLE
Some value can't be NULL

### ISSUE THREAD

**Issue by newebug** [aserg-ufmg/JSCity#2]
Good job!

I got the code and took a try just now, and found an error:

``` sql
INSERT INTO `tb_district`(`name`, `color`, `tooltip`, `city_id`) VALUES ('ai', NULL, 'Folder: ai', 3)
Failed to insert data in the database . Undoing transaction and ending the process.
```

The reason is: [Err] 1048 - Column 'color' cannot be null

**Comment by malilovick** [comment]
Hi , newebug 

There was a variable that was a wrong letter . Now the code is correct.  Thanks
